04_Web/webPage/config/urls.py
from django.contrib import admin
from django.urls import path
from Telco_defence import views  # 사용하고자 하는 app을 넣어주여야 url과 기능 연결 가능

urlpatterns = [
    path('admin/', admin.site.urls),  # 장고 자체 어드민 페이지
    path('', views.main_page_render, name='main-page'),  # 메인 페이지 렌더링
    path('list', views.customer_list, name='customer-list'),  # 리스트 페이지
    path('detail', views.customer_detail, name='customer-detail'),  # 세부 정보 페이지
    path('detail/<str:customer_ids>', views.customer_detail_selected, name='customer-detail-selected'),  # 리스트에서 선택했을때 접근
    path('detail/result/<str:customer_ids>', views.customer_detail_search, name='customer-detail-searched'),  # 검색했을때 접근
    path('dashboard', views.dashboard, name='dashboard'),  # 세부 정보 페이지
    path('administration', views.re_calc, name='administration_page'),
]

04_Web/webPage/Telco_defence/models.py
from django.db import models
from .module.choice_list import sas_choice, ms_choice, ct_choice, ts_choice, sts_choice, cp_choice, cpg_choice

# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.

""" Work log
231017, Model Create
231019, tbUser_CLTV Add
231019, Default Add
231021-22, Choice Add
231023, New migrate
"""


# Main Schema #######################################################
class TbUser(models.Model):  # User Table, 유저 테이블
    class Meta:
        verbose_name = '유저 테이블'
        verbose_name_plural = '유저 테이블'
        managed = False
        db_table = 'tb_user'

    customer_id = models.CharField(db_column='Customer_ID', verbose_name='고객 아이디', primary_key=True, max_length=10)
    age = models.IntegerField(db_column='Age', verbose_name='나이')
    satisfaction_score = models.IntegerField(db_column='Satisfaction_Score', verbose_name='고객 관리 점수', default=1, choices=sas_choice)  # 231022, default 0 > 1로 변경, 231022, choice 추가
    membership = models.CharField(db_column='Membership', verbose_name='멤버쉽', max_length=10, blank=True, null=True, choices=ms_choice)  # 231022, choice 추가
    cltv = models.BigIntegerField(db_column='CLTV', verbose_name="고객 점수", blank=True, null=True, default=1)  # 231019, CLTV column 추가 / 231022, default 추가
    churn_value = models.IntegerField(db_column='Churn_Value', verbose_name='해지 여부', blank=True, null=True, default=0)
    changed = models.IntegerField(db_column='Changed', verbose_name='변경 여부', blank=True, null=True, default=0)
    churn_proba = models.FloatField(db_column='Churn_proba', verbose_name='해지 확률', blank=True, null=True, default=0)  # 231022, Int > Float로 변경
    churn_proba_group = models.CharField(db_column='Churn_proba_group', verbose_name='관리 그룹', max_length=10, blank=True, null=True, default='Stable', choices=cpg_choice)  # 231023, choice 추가

    def __str__(self):  # 클래스의 정보를 name으로 호출하는 함수
        return f'{self.customer_id}'


class TbContract(models.Model):  # Contract Table, 요금제 정보 테이블
    class Meta:
        verbose_name = '요금제 정보'
        verbose_name_plural = '요금제 정보'
        managed = False
        db_table = 'tb_contract'

    customer = models.OneToOneField('TbUser', models.CASCADE, db_column='Customer_ID', verbose_name='고객 아이디', primary_key=True)
    contract = models.CharField(db_column='Contract', verbose_name='계약 종류', max_length=20, blank=True, null=True, choices=ct_choice)  # 231022, choice 추가
    tenure_in_months = models.BigIntegerField(db_column='Tenure_in_months', verbose_name='계약 개월 수', blank=True, null=True, default=1)  # 231022, default 추가
    monthly_charge = models.FloatField(db_column='Monthly_Charge', verbose_name='기본 요금', blank=True, null=True)
    total_revenue = models.FloatField(db_column='Total_Revenue', verbose_name='총 요금', blank=True, null=True)

    def __str__(self):  # 클래스의 정보를 name으로 호출하는 함수
        return f'{self.customer}'


class TbService(models.Model):  # Service Table, 서비스 정보 테이블
    class Meta:
        verbose_name = '서비스 정보'
        verbose_name_plural = '서비스 정보'
        managed = False
        db_table = 'tb_service'

    customer = models.OneToOneField('TbUser', models.CASCADE, db_column='Customer_ID', verbose_name='고객 아이디', primary_key=True)
    tech_services = models.IntegerField(db_column='Tech_services', verbose_name='기술 서비스', blank=True, null=True, choices=ts_choice)  # 231022, choice 추가
    streaming_services = models.IntegerField(db_column='Streaming_services', verbose_name='부가 서비스', blank=True, null=True, choices=sts_choice)  # 231022, choice 추가
    combined_product = models.IntegerField(db_column='Combined_Product', verbose_name='결합 상품 수', blank=True, null=True, choices=cp_choice)  # 231022, choice 추가
    number_of_dependents = models.IntegerField(db_column='Number_of_Dependents', verbose_name='가족 결합 수', blank=True, null=True)

    def __str__(self):  # 클래스의 정보를 name으로 호출하는 함수
        return f'{self.customer}'
# Main Schema End #######################################################


# Log Schema #######################################################
class TbUserLog(models.Model):  # User log Table, 유저 정보 변동 저장 테이블
    class Meta:
        verbose_name = '유저 수정 로그'
        verbose_name_plural = '유저 수정 로그'
        managed = False
        db_table = 'tb_user_log'

    customer = models.ForeignKey(TbUser, models.CASCADE, db_column='Customer_ID', verbose_name='고객 아이디')
    change_time = models.DateTimeField(db_column='Change_time', verbose_name='변경 시간', auto_now_add=True)
    age = models.IntegerField(db_column='Age', verbose_name='나이')
    satisfaction_score = models.IntegerField(db_column='Satisfaction_Score', verbose_name='고객 관리 점수', default=0)
    cltv = models.BigIntegerField(db_column='CLTV', blank=True, null=True, default=0)  # 231019, CLTV column 추가 대응
    churn_value = models.IntegerField(db_column='Churn_Value', verbose_name='해지 여부', blank=True, null=True, default=0)

    def __str__(self):  # 클래스의 정보를 name으로 호출하는 함수
        return f'{self.customer}'


class TbContractLog(models.Model):  # Contract log Table, 요금제 정보 변동 저장 테이블
    class Meta:
        verbose_name = '요금제 수정 로그'
        verbose_name_plural = '요금제 수정 로그'
        managed = False
        db_table = 'tb_contract_log'

    customer = models.ForeignKey(TbContract, models.CASCADE, db_column='Customer_ID', verbose_name='고객 아이디')
    change_time = models.DateTimeField(db_column='Change_time', verbose_name='변경 시간', auto_now_add=True)
    contract = models.CharField(db_column='Contract', verbose_name='계약 종류', max_length=20, blank=True, null=True)
    tenure_in_months = models.BigIntegerField(db_column='Tenure_in_months', verbose_name='계약 개월 수', blank=True, null=True)
    monthly_charge = models.FloatField(db_column='Monthly_Charge', verbose_name='기본 요금', blank=True, null=True)
    total_revenue = models.FloatField(db_column='Total_Revenue', verbose_name='총 요금', blank=True, null=True)

    def __str__(self):  # 클래스의 정보를 name으로 호출하는 함수
        return f'{self.customer}'


class TbServiceLog(models.Model):  # Service log Table, 서비스 정보 변동 저장 테이블
    class Meta:
        verbose_name = '서비스 수정 로그'
        verbose_name_plural = '서비스 수정 로그'
        managed = False
        db_table = 'tb_service_log'

    customer = models.ForeignKey(TbService, models.CASCADE, db_column='Customer_ID', verbose_name='고객 아이디')
    change_time = models.DateTimeField(db_column='Change_time', verbose_name='변경 시간', auto_now_add=True)
    tech_services = models.IntegerField(db_column='Tech_services', verbose_name='기술 서비스', blank=True, null=True)
    streaming_services = models.IntegerField(db_column='Streaming_services', verbose_name='부가 서비스', blank=True, null=True)
    combined_product = models.IntegerField(db_column='Combined_Product', verbose_name='결합 상품 수', blank=True, null=True)
    number_of_dependents = models.IntegerField(db_column='Number_of_Dependents', verbose_name='가족 결합 수', blank=True, null=True)

    def __str__(self):  # 클래스의 정보를 name으로 호출하는 함수
        return f'{self.customer}'
# Log Schema End #######################################################


# User Statistics Schema
class TbUserAgeRange(models.Model):
    class Meta:
        verbose_name = '나이대'
        verbose_name_plural = '나이대'
        managed = False
        db_table = 'tb_user_age_range'

    under_10 = models.BigIntegerField(db_column='Under_10', blank=True, null=True)
    age_10 = models.BigIntegerField(db_column='Age_10', blank=True, null=True)
    age_20 = models.BigIntegerField(db_column='Age_20', blank=True, null=True)
    age_30 = models.BigIntegerField(db_column='Age_30', blank=True, null=True)
    age_40 = models.BigIntegerField(db_column='Age_40', blank=True, null=True)
    age_50 = models.BigIntegerField(db_column='Age_50', blank=True, null=True)
    age_60 = models.BigIntegerField(db_column='Age_60', blank=True, null=True)
    age_70 = models.BigIntegerField(db_column='Age_70', blank=True, null=True)
    age_80 = models.BigIntegerField(db_column='Age_80', blank=True, null=True)
    age_90 = models.BigIntegerField(db_column='Age_90', blank=True, null=True)


class TbUserCv(models.Model):
    class Meta:
        verbose_name = '해지 카테고리'
        verbose_name_plural = '해지 카테고리'
        managed = False
        db_table = 'tb_user_cv'

    churned = models.BigIntegerField(db_column='Churned', blank=True, null=True)
    stayed = models.BigIntegerField(db_column='Stayed', blank=True, null=True)


class TbUserSs(models.Model):
    class Meta:
        verbose_name = '관리 점수'
        verbose_name_plural = '관리 점수'
        managed = False
        db_table = 'tb_user_ss'

    ss_0 = models.BigIntegerField(db_column='SS_0', blank=True, null=True)
    ss_1 = models.BigIntegerField(db_column='SS_1', blank=True, null=True)
    ss_2 = models.BigIntegerField(db_column='SS_2', blank=True, null=True)
    ss_3 = models.BigIntegerField(db_column='SS_3', blank=True, null=True)
    ss_4 = models.BigIntegerField(db_column='SS_4', blank=True, null=True)
    ss_5 = models.BigIntegerField(db_column='SS_5', blank=True, null=True)

class TbUserCltv(models.Model):  # 231019, CTLV column 추가로 인한 통계 테이블 추가
    class Meta:
        verbose_name = '고객 점수'
        verbose_name_plural = '고객 점수'
        managed = False
        db_table = 'tb_user_cltv'

    cltv_0 = models.BigIntegerField(blank=True, null=True)
    cltv_1 = models.BigIntegerField(blank=True, null=True)
    cltv_2 = models.BigIntegerField(blank=True, null=True)
    cltv_3 = models.BigIntegerField(blank=True, null=True)
    cltv_4 = models.BigIntegerField(blank=True, null=True)
    cltv_5 = models.BigIntegerField(blank=True, null=True)

04_Web/webPage/Telco_defence/templates/administrator.html
{# 관리자 페이지 #}
{# 모델 업데이트, 확률 재계산 등의 동작 페이지 #}
{# 사용 여부 미지수 #}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="post"> {% csrf_token %}
        <input type="submit" value="update" placeholder="update" name="order">
    </form>

    <form method="post"> {% csrf_token %}
        <input type="submit" value="recalc" name="order">
    </form>
</body>
</html>

04_Web/webPage/Telco_defence/templates/dashboard.html
{% load static %}
<html lang="ko">
<head>
    <meta charset="utf-8">
    <title>Dashboard | Telcodefence</title>
    <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="./static/css/styles.css">
    <style>
    /* Figma Background for illustrative/preview purposes only.
        You can remove this style tag with no consequence */
    body {background: #E5E5E5; }
    </style>
</head>

<body>
    <div class=e29_946 description="전체">
        <div  class="e64_472" description="전체"></div>
        <div  class="e64_484" description="드롭다운 들어갈 자리">
            <form method="GET" class="form_block">
                <span class="now_infor"><img style="display:inline; width:400px; height:80px;" src="{{ now_view }}"></span>
                <select class="dashboard_dropdown" name="dropdown_select">
                    <option value="user">사용자 정보</option>
                    <option value="service">서비스 정보</option>
                    <option value="contract">요금제 정보</option>
                </select>
                <input class="dashboard_post_submit" type="submit" value="">
            </form>
        </div>

        <div class=e64_509> <!-- 전체 현황 시각화 부분 -->
            <span  class="e64_492">{{ title1 }}</span>
            <span  class="e64_493">{{ desc1 }}</span>
        </div>
        <div  class="e31_1732" description="전체1 시각화 그림">
            <img style="display:inline; width:100%; height:100%;" src="/static/images/dashboard_output/output_0.png">
        </div>

        <div class=e64_510>
            <span  class="e64_494">{{ title2 }}</span>
            <span  class="e64_495">{{ desc2 }}</span>
        </div>
        <div  class="e64_477" description="전체2 시각화 그림">
            <img style="display:inline; width:100%; height:100%;" src="/static/images/dashboard_output/output_1.png">
        </div>

        <div class=e64_511>
            <span  class="e64_496">{{ title3 }}</span>
            <span  class="e64_497">{{ desc3 }}</span>
        </div>
        <div  class="e64_478" description="전체3 시각화 그림">
            <img style="display:inline; width:100%; height:100%;" src="/static/images/dashboard_output/output_2.png">
        </div>

        <div class=e64_512>
            <span  class="e64_498">{{ title4 }}</span>
            <span  class="e64_499">{{ desc4 }}</span>
        </div>
        <div  class="e64_479" description="전체4 시각화 그림">
            <img style="display:inline; width:100%; height:100%;" src="/static/images/dashboard_output/output_3.png">
        </div> <!-- 여기까지 전체 현황 시각화 부분입니다 -->

        <div class=e64_513 description="상관관계 시각화 제목&설명"> <!-- 상관관계 시각화 부분 -->
            <span  class="e64_500">{{ title5 }}</span>
            <span  class="e64_501">{{ desc5 }}</span>
        </div>
        <div  class="e64_480" description="상관관계0 시각화 그림">
            <img style="display:inline; width:100%; height:100%;" src="/static/images/dashboard_output/output_4.png">
        </div>

        <div class=e64_514 >
            <span  class="e64_502">{{ title6 }}</span>
            <span  class="e64_503">{{ desc6 }}</span>
        </div>
        <div  class="e64_481" description="상관관계2 시각화 그림">
            <img style="display:inline; width:100%; height:100%;" src="/static/images/dashboard_output/output_5.png">
        </div>

        <div class=e64_515 >
            <span  class="e64_504">{{ title7 }}</span>
            <span  class="e64_505">{{ desc7 }}</span>
        </div>
        <div  class="e64_482" description="상관관계3 시각화 그림">
            <img style="display:inline; width:100%; height:100%;" src="/static/images/dashboard_output/output_6.png">
        </div>

        <div class=e64_516>
            <span  class="e64_506">{{ title8 }}</span>
            <span  class="e64_507">{{ desc8 }}</span> 
        </div> 
        <div  class="e64_483" description="상관관계4 시각화 그림">
            <img style="display:inline; width:100%; height:100%;" src="/static/images/dashboard_output/output_7.png">
        </div> <!-- 여기까지 상관관계 분석 시각화 부분입니다 -->

        <div class=e64_473 description="세부페이지 바로가기 묶음">
            <a href="{% url 'customer-detail' %}"  class="e64_474" description="세부 고객 정보 바로가기"></a>
            <a href="{% url 'customer-list' %}"  class="e64_475" description="고객 이탈 예측 관리 바로가기"></a>
            <a href="{% url 'dashboard' %}"  class="e64_476" description="종합 정보 시각화 바로가기"></a>
        </div>
    </div>

    <a href="{% url 'main-page' %}" class="e20_1588" description="홈페이지 바로가기"></a>
</body>
</html>

04_Web/webPage/Telco_defence/templates/detail.html
{% load static %}
<html lang="ko">
<head>
    <meta charset="utf-8">
    <title>Detail Page | Telcodefence</title>
    <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
    {% if c_id is None %}
        <link rel="stylesheet" href="./static/css/styles.css">
    {% else %}
        <link rel="stylesheet" href="../../static/css/styles.css">
    {% endif %}

    <style>
    /* Figma Background for illustrative/preview purposes only.
        You can remove this style tag with no consequence */
    body {background: #E5E5E5; }
    </style>
</head>

<body>
    <div class=e20_1448 description="전체">
        <div  class="e63_319" description="전체2"></div>
        <span id="market_recom" class="e20_1574" description="마케팅 내용">자세한 마케팅 방안을 확인하려면 제안보기 버튼을 클릭하세요</span>
        {% for dt in data%}

            {% if dt.churn_proba_group == "Stable" %}
                <span class="churn_proba" description="해지 확률"><span style="color: green">{{dt.churn_proba|floatformat:2}}</span>%, {{dt.get_churn_proba_group_display}}</span>
            {% elif dt.churn_proba_group == "Potential" %}
                <span class="churn_proba" description="해지 확률"><span style="color: orange">{{dt.churn_proba|floatformat:2}}</span>%, {{dt.get_churn_proba_group_display}}</span>
            {% elif dt.churn_proba_group == "High" %}
                <span class="churn_proba" description="해지 확률"><span style="color: red">{{dt.churn_proba|floatformat:2}}</span>%, {{dt.get_churn_proba_group_display}}</span>
            {% endif %}

            <span class="e62_270" description="총 요금 텍스트">{{dt.tbcontract.total_revenue}}</span>
            <span class="e62_269" description="월 요금 텍스트">{{dt.tbcontract.monthly_charge}}</span>
            <span class="e62_268" description="계약 기간 텍스트">{{dt.tbcontract.tenure_in_months}}</span>
            <span class="e62_267" description="계약 형태 텍스트">{{dt.tbcontract.get_contract_display}}</span>
            <span class="e62_266" description="통신 결합 이용 개수 텍스트">{{dt.tbservice.get_combined_product_display}}</span>
            <span class="e62_265" description="가족 결합 이용자 수 텍스트">{{dt.tbservice.number_of_dependents}}</span>
            <span class="e62_264" description="부가 서비스 이용 개수 텍스트">{{dt.tbservice.get_streaming_services_display}}</span>
            <span class="e62_263" description="기술 서비스 이용 개수 텍스트">{{dt.tbservice.get_tech_services_display}}</span>
            <span class="e62_262" description="CLTV 텍스트">{{dt.cltv}}</span>
            <span class="e62_261" description="멤버십 단계 텍스트">{{dt.get_membership_display}}</span>
            <span class="e62_260" description="고객 관리 점수 텍스트">{{dt.get_satisfaction_score_display}}</span>
            <span class="e62_244" description="나이 텍스트">{{dt.age}}</span>
        {% endfor %}

        <button onclick="document.getElementById('market_recom').innerHTML='{{text}}'"  class="e62_240" description="마케팅 제안 보기">
        <div  class="e62_308" description="마케팅 제안 보기"></div>
    </div>

    {% if c_id is None %}
        <form action="{% url 'customer-detail-searched' c_id %}" method="GET">
            <input type="text" class="e29_9" description="고객 아이디 입력 텍스트" placeholder="고객 아이디를 입력하세요" name="input_cs_id" list="iddata">
            <input class="detail_submit" type="submit" value="">
        </form>
    {% else %}
        <form action="{% url 'customer-detail-searched' c_id %}" method="GET">
            <input type="text" class="e29_9" description="고객 아이디 입력 텍스트" value="{{c_id}}" name="input_cs_id" list="iddata">
            <input class="detail_submit" type="submit" value="">
        </form>
    {% endif %}

    <div class=e62_306 description="세부페이지 바로가기 묶음">
        <a href="{% url 'customer-detail' %}" class="e62_274" description="세부 고객 정보 바로가기"></a>
        <a href="{% url 'customer-list' %}" class="e62_304" description="고객 이탈 예측 관리 바로가기"></a>
        <a href="{% url 'dashboard' %}" class="e62_305" description="종합 정보 시각화 바로가기"></a>
    </div>

    <a href="{% url 'main-page' %}" class="e20_1588" description="홈페이지 바로가기"></a>
    <datalist id="iddata">
        {% for dt in list_data %}
            <option value="{{ dt.customer_id }}"></option>
        {% endfor %}
    </datalist>
    </div>
</body>
</html>

04_Web/webPage/Telco_defence/templates/home.html
{% load static %}
<html lang="ko">
<head>
    <meta charset="utf-8">
    <title>Home | Telcodefence</title>
    <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="./static/css/styles.css">

    <style>
    /* Figma Background for illustrative/preview purposes only.
        You can remove this style tag with no consequence */
    body {background: #E5E5E5; }
    </style>
</head>

<body>
    <div class=e29_980 description="전체">
        <div  class="e30_1180" description="전체2"></div>
        <div class=e31_1181 description="버튼 모음"> 
            <div class=e31_1182 description="1번째 click">
                <a href="{% url 'customer-detail' %}" class="ei31_1182_130_99" description="1번째 click"></a>
                <a href="{% url 'customer-detail' %}" style="text-decoration: none;" class="ei31_1182_130_100" description="1번째 click 텍스트">Click !</a>
            </div>

            <div class=e31_1183 description="2번째 click">
                <a href="{% url 'customer-list' %}" class="ei31_1183_130_99" description="2번째 click"></a>
                <a href="{% url 'customer-list' %}" style="text-decoration: none;" class="ei31_1183_130_100" description="2번째 click 텍스트">Click !</a>
            </div>

            <div class=e31_1184 description="3번째 click">
                <a href="{% url 'dashboard' %}" class="ei31_1184_130_99" description="3번째 click"></a>
                <a href="{% url 'dashboard' %}" style="text-decoration: none;" class="ei31_1184_130_100" description="3번째 click 텍스트">Click !</a>
            </div>
        </div>
    </div>
</body>
</html>

04_Web/webPage/Telco_defence/templates/list.html
{% load static %}
<html lang="ko">
<head>
    <meta charset="utf-8">
    <title>Customer List | Telcodefence</title>
    <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="./static/css/styles.css">

    <style>
    /* Figma Background for illustrative/preview purposes only.
        You can remove this style tag with no consequence */
    body {background: #E5E5E5; }
    </style>
</head>

<body>
    <div class="e29_920" description="전체">
        <div class="e63_334" description="전체"></div>
        <!-- <div class="spacer-list"></div> {# 추가함 #} -->
    </div>

        <form method="GET"> {#{% csrf_token %}#}
            <select class="list_filter" name="filtering_order">
                <option value="all">- 선택 -</option>
                <option value="total">모두 보기</option>
                <option value="all">---- 이탈률 ----</option>
                <option value="upper40">이탈 40% 이상</option>
                <option value="upper60">이탈 60% 이상</option>
                <option value="all">---- 위험군 ----</option>
                <option value="potential">잠재 이탈 위험군</option>
                <option value="high">이탈 고위험군</option>
            </select>
            <input class="list_filter_submit" type="submit" value="">
        </form>

        {% if filtering_order_name and filtering_order_name != '전체 보기' %}
            <span style="display: inline-block; top:360px; left:1200px; position:absolute;">필터 : {{filtering_order_name}}</span>
        {% endif %}

    {% for data in lines %}
    <div class="e49_196" description="출력값 묶음"> {# 수정함 #}
        <span class="e42_3404" description="customerid 출력값"> {# 수정함 #}
            <a href="{% url 'customer-detail-selected' data.customer_id %}" class="e42_3405" description="customerid 출력값 텍스트">{{data.customer_id}}</a>
        </span>
        
        <span class=e49_192 description="이탈 확률 출력값"> 
            <span  class="e49_193" description="이탈 확률 출력값 텍스트">{{data.churn_proba|floatformat:4}} %</span>
        </span>

        <span class=e49_194 description="이탈 그룹 출력값">
            {% if data.churn_proba_group == "Stable" %}
                <span  class="e49_195" description="이탈 그룹 출력값 텍스트"><span>{{data.get_churn_proba_group_display}} 그룹</span></span>
            {% elif data.churn_proba_group == "Potential" %}
                <span  class="e49_195" description="이탈 그룹 출력값 텍스트"><span style="color: orange">{{data.get_churn_proba_group_display}} 그룹</span></span>
            {% elif data.churn_proba_group == "High" %}
                <span  class="e49_195" description="이탈 그룹 출력값 텍스트"><span style="color: red">{{data.get_churn_proba_group_display}} 그룹 </span></span>
            {% endif %}
        </span>

            <!-- <span  class="e49_195" description="이탈 그룹 출력값 텍스트"><span>{{data.get_churn_proba_group_display}}</span> 그룹</span> -->
    </div>
    {% endfor %}

    <div class=e64_485 description="평균이탈확률, 트레이닝 정확도 묶음"> {# 수정함 #}
        <span  class="e31_1932" description="평균이탈확률 텍스트">{{ proba_avg|floatformat:4 }}</span>
    </div>

    <div class=e63_335 description="세부페이지 바로가기 묶음"> {# 수정함 #}
        <a href="{% url 'customer-detail' %}" class="e63_336" description="세부 고객 정보 바로가기"></a>
        <a href="{% url 'customer-list' %}" class="e63_337" description="고객 이탈 예측 관리 바로가기"></a>
        <a href="{% url 'dashboard' %}" class="e63_338" description="종합 정보 시각화 바로가기"></a>
    </div>

    <a href="{% url 'main-page' %}" class="e20_1588" description="홈페이지 바로가기"></a>

    <div class="pagination"> {# 추가함 #}
        {% include "pagination_block.html" %}
        {% block paginator %}
        {% endblock %}
    </div>
</body>
</html>

04_Web/webPage/Telco_defence/templates/pagination_block.html
{# Paginator 블록 #}
{# 사용을 위해선 탬플릿에 {% include "pagination_block.html" %} {% block paginator %} {% endblock %}추가 #}
{% block pagination %}
{% if lines.has_other_pages %}
    {# <div>now page : {{ lines.number }}</div> #}
    <span class = "pagination">
        {% if lines.has_previous %}
            <a href="?page=1">처음 페이지</a>
            <a href="?page={{ lines.previous_page_number }}">&laquo;</a>
        {% else %}
            <span class = "disabled"><span>&laquo;</span></span>
        {% endif %}

        {#{% for i in paginator.page_range %}#}
        {% for i in custom_range %}
            {% if lines.number == i %}
                <span class="active"><span>{{ i }}</span></span>
            {% else %}
                <span><a href="?page={{ i }}">{{ i }}</a></span>
            {% endif %}
        {% endfor %}

        {% if lines.has_next %}
            {% if lines.number >= paginator_idx %}
                <a href="?page={{ lines.next_page_number }}">&raquo;</a>
            {% else %}
                <span>...</span>
                <a href="?page={{ lines.next_page_number }}">&raquo;</a>
                <a href="?page={{ end_page }}">마지막 페이지</a>
            {% endif %}

        {% else %}
            <span class="disabled"><span>&raquo;</span></span>
        {% endif %}
    </span>
{% endif %}
{% endblock %}